### ISSUE TITLE
当使用白色主题时，第一个候选词太亮

### ISSUE THREAD

**Issue by Jaggle** [libpinyin/ibus-libpinyin#84]
![default](https://user-images.githubusercontent.com/5469845/29250096-f25832aa-806e-11e7-85b4-680f8255abac.png)

**Comment by epico** [comment]
建议自行修改 gnome shell 的主题。

可以参考：
https://pwu.fedorapeople.org/ibus/gnome-ibus/

**Comment by epico** [comment]
请问你的桌面环境是？

**Comment by Jaggle** [comment]
@epico 非常感谢你的提醒，目前修改了我的样式文件gnome-shell.css

```css
.candidate-box:selected {
    color: #000;
    border-radius: 4px;
    background-color: rgba(255,255,255,0.2);
}
```
这样就可以将第一个候选词变成黑色。

---

我使用的fedora 25/26 gnome3
